# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_Date', models.DateTimeField()),
                ('out_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUp_name', models.CharField(max_length=150)),
                ('signUp_E_mail', models.CharField(max_length=150)),
                ('signUp_Car_model', models.CharField(max_length=150)),
                ('signUp_Car_number', models.CharField(max_length=150)),
                ('signUp_Car_color', models.CharField(max_length=150)),
                ('signUp_Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserSignUp'),
        ),
    ]
