# Generated by Django 2.0 on 2017-12-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
